import Foundation

struct PiExtensionInstaller {
    let extensionURL: URL
    let adderailURL: URL

    static func defaultExtensionURL() -> URL {
        let environment = ProcessInfo.processInfo.environment
        if let extensionPath = environment["ADDERAIL_PI_EXTENSION_PATH"], extensionPath.isEmpty == false {
            return URL(fileURLWithPath: NSString(string: extensionPath).expandingTildeInPath)
        }

        return FileManager.default.homeDirectoryForCurrentUser
            .appendingPathComponent(".pi", isDirectory: true)
            .appendingPathComponent("agent", isDirectory: true)
            .appendingPathComponent("extensions", isDirectory: true)
            .appendingPathComponent("adderail", isDirectory: true)
            .appendingPathComponent("index.ts")
    }

    func prepareInstall() throws -> PiExtensionPlan {
        let extensionExisted = FileManager.default.fileExists(atPath: extensionURL.path)

        if extensionExisted {
            let currentContent = try String(contentsOf: extensionURL, encoding: .utf8)
            guard Self.isAdderailExtension(currentContent) else {
                throw InstallerError.piExtensionConflict(extensionURL)
            }
        }

        return PiExtensionPlan(
            content: Self.extensionContent(adderailURL: adderailURL),
            extensionExisted: extensionExisted
        )
    }

    func install() throws -> PiExtensionChange {
        try install(preparedPlan: prepareInstall())
    }

    func install(preparedPlan: PiExtensionPlan) throws -> PiExtensionChange {
        if FileManager.default.fileExists(atPath: extensionURL.path) {
            let currentContent = try String(contentsOf: extensionURL, encoding: .utf8)
            if currentContent == preparedPlan.content {
                return PiExtensionChange(
                    extensionURL: extensionURL,
                    extensionExisted: preparedPlan.extensionExisted,
                    didChange: false
                )
            }
        }

        try FileManager.default.createDirectory(
            at: extensionURL.deletingLastPathComponent(),
            withIntermediateDirectories: true
        )
        try preparedPlan.content.write(to: extensionURL, atomically: true, encoding: .utf8)

        return PiExtensionChange(
            extensionURL: extensionURL,
            extensionExisted: preparedPlan.extensionExisted,
            didChange: true
        )
    }

    func uninstall() throws -> PiExtensionChange {
        guard FileManager.default.fileExists(atPath: extensionURL.path) else {
            return PiExtensionChange(
                extensionURL: extensionURL,
                extensionExisted: false,
                didChange: false
            )
        }

        let currentContent = try String(contentsOf: extensionURL, encoding: .utf8)
        guard Self.isAdderailExtension(currentContent) else {
            throw InstallerError.piExtensionConflict(extensionURL)
        }

        try FileManager.default.removeItem(at: extensionURL)
        try removeParentDirectoryIfEmpty()

        return PiExtensionChange(
            extensionURL: extensionURL,
            extensionExisted: true,
            didChange: true
        )
    }

    func isInstalled() throws -> Bool {
        guard FileManager.default.fileExists(atPath: extensionURL.path) else {
            return false
        }

        let currentContent = try String(contentsOf: extensionURL, encoding: .utf8)
        return Self.isAdderailExtension(currentContent)
    }

    private func removeParentDirectoryIfEmpty() throws {
        let directoryURL = extensionURL.deletingLastPathComponent()
        let contents = try FileManager.default.contentsOfDirectory(at: directoryURL, includingPropertiesForKeys: nil)

        if contents.isEmpty {
            try FileManager.default.removeItem(at: directoryURL)
        }
    }

    private static func isAdderailExtension(_ content: String) -> Bool {
        content.contains(marker)
    }

    private static let marker = "ADDERAIL_PI_EXTENSION"

    private static func extensionContent(adderailURL: URL) -> String {
        let adderailPath = jsonStringLiteral(adderailURL.path)

        return """
        // generated by Adderail. remove with: adderail uninstall pi
        // \(marker)

        import process from "node:process";
        import type { ExtensionAPI, ExtensionContext } from "@earendil-works/pi-coding-agent";

        const ADDERAIL = \(adderailPath);
        const PROVIDER = "pi";
        const STATUS_KEY = "adderail";
        const DEFAULT_TTL_SECONDS = 300;
        const TOOL_TIMEOUT_BUFFER_SECONDS = 60;

        let active = false;
        let lastRequestSucceeded = true;
        let lastSessionID: string | undefined;

        export default function adderail(pi: ExtensionAPI) {
            pi.on("session_start", async (_event, ctx) => {
                updateStatus(ctx);
            });

            pi.on("agent_start", async (_event, ctx) => {
                const sessionID = sessionIDFor(ctx);
                active = true;
                lastSessionID = sessionID;
                lastRequestSucceeded = await send(pi, ctx, ["begin", "--provider", PROVIDER, "--session", sessionID, "--ttl", String(DEFAULT_TTL_SECONDS)]);
                updateStatus(ctx);
            });

            pi.on("tool_execution_start", async (event, ctx) => {
                if (!active) return;
                const sessionID = lastSessionID ?? sessionIDFor(ctx);
                lastRequestSucceeded = await send(pi, ctx, ["heartbeat", "--provider", PROVIDER, "--session", sessionID, "--ttl", String(toolTTLSeconds(event))]);
                updateStatus(ctx);
            });

            pi.on("tool_execution_end", async (_event, ctx) => {
                if (!active) return;
                const sessionID = lastSessionID ?? sessionIDFor(ctx);
                lastRequestSucceeded = await send(pi, ctx, ["heartbeat", "--provider", PROVIDER, "--session", sessionID, "--ttl", String(DEFAULT_TTL_SECONDS)]);
                updateStatus(ctx);
            });

            pi.on("agent_end", async (_event, ctx) => {
                const sessionID = lastSessionID ?? sessionIDFor(ctx);
                await send(pi, ctx, ["end", "--provider", PROVIDER, "--session", sessionID]);
                active = false;
                lastRequestSucceeded = true;
                lastSessionID = undefined;
                updateStatus(ctx);
                ctx.ui.notify("Released adderail (agent finished).", "info");
            });

            pi.on("session_shutdown", async (_event, ctx) => {
                const sessionID = lastSessionID ?? sessionIDFor(ctx);
                await send(pi, ctx, ["end", "--provider", PROVIDER, "--session", sessionID], { notify: false });
                active = false;
                lastRequestSucceeded = true;
                lastSessionID = undefined;
                ctx.ui.setStatus(STATUS_KEY, undefined);
            });
        }

        function sessionIDFor(ctx: ExtensionContext) {
            return ctx.sessionManager.getSessionFile() ?? `${ctx.cwd}:${process.pid}`;
        }

        function toolTTLSeconds(event: { args?: Record<string, unknown> }) {
            const timeout = event.args?.timeout;
            if (typeof timeout !== "number" || timeout <= 0) {
                return DEFAULT_TTL_SECONDS;
            }

            return Math.max(DEFAULT_TTL_SECONDS, Math.ceil(timeout) + TOOL_TIMEOUT_BUFFER_SECONDS);
        }

        async function send(pi: ExtensionAPI, ctx: ExtensionContext, args: string[], options: { notify?: boolean } = {}) {
            try {
                const result = await pi.exec(ADDERAIL, args, { timeout: 1000 });
                if (result.code === 0) {
                    return true;
                }

                const output = (result.stderr || result.stdout || `adderail exited with ${result.code}`).trim();
                if (options.notify !== false) {
                    ctx.ui.notify(`Adderail Pi integration failed: ${output}`, "warning");
                }
            } catch (error) {
                const message = error instanceof Error ? error.message : String(error);
                if (options.notify !== false) {
                    ctx.ui.notify(`Adderail Pi integration failed: ${message}`, "warning");
                }
            }

            return false;
        }

        function updateStatus(ctx: ExtensionContext) {
            if (active && lastRequestSucceeded) {
                ctx.ui.setStatus(STATUS_KEY, "awake");
                return;
            }

            if (active) {
                ctx.ui.setStatus(STATUS_KEY, "unavailable");
                return;
            }

            ctx.ui.setStatus(STATUS_KEY, undefined);
        }
        """
    }

    private static func jsonStringLiteral(_ value: String) -> String {
        let data = try? JSONSerialization.data(withJSONObject: [value], options: [.withoutEscapingSlashes])
        let json = data.flatMap { String(data: $0, encoding: .utf8) } ?? "[\"\"]"
        return String(json.dropFirst().dropLast())
    }
}

struct PiExtensionPlan {
    let content: String
    let extensionExisted: Bool
}

struct PiExtensionChange {
    let extensionURL: URL
    let extensionExisted: Bool
    let didChange: Bool
}
